### ISSUE TITLE
Cool script but the..

### ISSUE THREAD

**Issue by xxUnknown13xx** [Randolio/randol_cityworker#1]
The animation of the hammer doesnt work :( He just stands there without any animation.

**Comment by Randolio** [comment]
Works for me and everyone else. Must be an issue on your end.

**Comment by xxUnknown13xx** [comment]
Probably you’re right but either way, I like it! 😎 thank you for this

**Comment by Randolio** [comment]
What emote menu are you using?

**Comment by xxUnknown13xx** [comment]
I’m using RPEmotes

**Comment by Randolio** [comment]
Should still work unless they changed how they trigger emotes.

**Comment by MissTweekaNL** [comment]
Hello
I've installed the job, but when I drive to a location, I don't see anything at the location itself.
How does this job work?

Best regards
MissTweeka
